version: "3.7"
services:
  #
  # Customer Microservice
  # 
  customer-ms:
    build:
      context: ./customer
    container_name: customer-ms
    ports:
      - "8102:8102"
    depends_on:
      - mongodb_db

  mongodb_db:
    image: mongo:latest
    container_name: customer-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: customer_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    
  #
  #Book Microservice
  #
  book-ms:
    build:
      context: ./book
    container_name: book-ms
    ports:
      - "8102:8102"
    depends_on:
      - mongodb_db

  mongodb_db:
    image: mongo:latest
    container_name: book-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: book_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  


  #
  # Borrowing Microservice
  #
  borrowing-ms:
    build:
      context: ./book
    container_name: borrowing-ms
    ports:
      - "8102:8102"
    depends_on:
      - mongodb_db

  mongodb_db:
    image: mongo:latest
    container_name: borrowing-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: borrowing_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  #
  # Notification
  #
  notification-ms:
    build:
      context: ./notification
    container_name: notification-ms
    ports:
      - "8104:8104"
    depends_on:
      - kafka

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    image: bitnami/kafka
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"

  


volumes:
 mongodb_data: {}
 postgres_data: {}